export const homeObjOne = {
  id: 'about',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: '',
  headline: 'Prazer, Daniel Moura.',
  description: 'Criador do JardimReal, paisagista, amante do design biofílico, especialista em Jardins Verticais de Alto Padrão. Conecto pessoas à natureza, promovendo bem-estar físico e mental, garantindo exatidão e excelência de forma única à cada cliente.',
  buttonLabel: 'PEÇA UM ORÇAMENTO',
  imgStart: true,
  img: require('../../images/img-about.png'),
  alt: 'Car',
  dark: false,
  primary: false,
  darkText: true,
};
